### ISSUE TITLE
I have an Idea

### ISSUE THREAD

**Issue by Zenogener** [jman1593/strongdog#1]
This should be very easy to code because I code stuff myself but you should add a setting where you can set a panic button which the user can set to any key and then if a person presses that key that they set it will exit out of the website so a teacher does not see them. But it must be a button they vary rarely press and maybe it can even be a combination for example shift+x. I understand that you switched to another website but I am issuing it here because I could not find that other respiratory.

**Comment by jman1593** [comment]
ik. i thought about  doing that but decided not to. i might later tho.

**Comment by jman1593** [comment]
also, i privated the other repo so people cant steal my code (im looking at you maximus weichers)

**Comment by Zenogener** [comment]
Lol He literally steals everything from everyone and sits next to me. and he is weird.

**Comment by jman1593** [comment]
yeah.

**Comment by jman1593** [comment]
and he claims it as his own too. he keeops claiming to have created strongdog.

**Comment by Zenogener** [comment]
Well thanks for replying

**Comment by jman1593** [comment]
i might add it anyways tho
