### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by Zenogener** [jman1593/strongdog#2]
Max is claiming is is the real owner,can you verify this is false, plus he has no evidence, lol. He is raging and almost broke the teachers chromebook, please give me evidence of how this is false So  I can tell him he is wrong.

**Comment by jman1593** [comment]
ok, first, I have ownership of the private GitHub domain. I'll show u a pic. second, max hasn't had access to strongdog for like 1 year, and when I did the recent redesign, I removed all his code so he has no part In strongdog. (this next part will make him rage if u tell it to him.) he is making a new site that all it is is strongdog downloaded, and he re branded it (changed colors and made a different name in the intro animation to games.) when it comes out, you can see the animation. its literly my old one (not the better new 1) but it has astroXP instead of strongdogXP. also, here is the image of the jman privated repo. also, a pic of the collaborators tab (where I can share private repos for people to help me) its empty.
![Screenshot 2024-03-13 1 23 39 PM](https://github.com/jman1593/strongdog/assets/95952762/98783481-000b-4c28-83ab-0df591b2f78c)
![Screenshot 2024-03-13 1 22 57 PM](https://github.com/jman1593/strongdog/assets/95952762/80d8326a-099e-46a3-8d75-2248f3e1e256)

**Comment by Zenogener** [comment]
He is raging so hard rn

**Comment by jman1593** [comment]
ik. he came and started yelling at me for "sending people to confront him" when you just asked some inf, I never said to do anything. ;D

**Comment by Zenogener** [comment]
Well, sorry then

**Comment by jman1593** [comment]
naw, ur chill, it was kind of funny.

**Comment by Zenogener** [comment]
Now bro  is asking me to help him make his "AstroXP" aka copy of strongdog. And I'm  refusing, either way he wont be able to  make it more popular than strongdog and plus no one will care about something made by max

**Comment by jman1593** [comment]
yeah. Also, once I start going on adding games again, I'll be adding like 5 or more a day, and there is no one he is beating that.

**Comment by jman1593** [comment]
and wait, he asked you to help him? that's kind of funny ngl.

**Comment by jman1593** [comment]
also, thank you for not just taking his side and believing me for once, because I have so many people hate on me and tell me to go kill myself because they think I stole max's code instead of him taking mine.

**Comment by jman1593** [comment]
also, who are you irl?

**Comment by Zenogener** [comment]
Why? You probably don't know me.  but either way if you respond I'll give it to you. also if you want Ill give you a working proxy if you don't already have one. But you cant give it to anyone or it will be blocked.

**Comment by jman1593** [comment]
I was just wondering. Also, I have like 5 proxies that work

**Comment by Zenogener** [comment]
My  name is Tristan

**Comment by Zenogener** [comment]
Oh and Guess waht

**Comment by Zenogener** [comment]
Max sent one of my friends a file for strong dog DOWNLOADED, which verifies everything you said.

**Comment by Zenogener** [comment]
And apparently he is using it.

**Comment by jman1593** [comment]
cool

**Comment by jman1593** [comment]
yeah, i still have the downloaded version

**Comment by Zenogener** [comment]
Max is spreading so much false rumors about you.

**Comment by Zenogener** [comment]
And as usually he just slammed his Chromebook 10 minutes before class ended and just left.

**Comment by jman1593** [comment]
can you tell me all the rumors you know?

**Comment by Zenogener** [comment]
He says he "Taught" You code. He also says you use chatgpt for all code. He then says you stole his code and he says his code is still in there.

**Comment by Zenogener** [comment]
Me and an 8th grader named sawyer are both proving him false with everything he says. And I don't even care if you did not make it or if you copied his code or stole it from him, I'm not saying you are but if you did, you made a good decision because max I so stupid he even thinks Canada is not a country.

**Comment by Zenogener** [comment]
Anyways tomorrow in class I'm gonna secretly record him and then send it to you.

**Comment by jman1593** [comment]
buddy

**Comment by jman1593** [comment]
ok, thank you. also, i was saying buddy to what max is saying. also, i did make the code, he is just very jealous. its kind of funny, he avoids me in the halls cuz i can prove him wrong on all that crap and he knows that i hear about what he says.

**Comment by Zenogener** [comment]
lol

**Comment by jman1593** [comment]
do u got a discord

**Comment by Zenogener** [comment]
yeh

**Comment by Zenogener** [comment]
I do

**Comment by jman1593** [comment]
what is it

**Comment by jman1593** [comment]
mine is regentstew

**Comment by Zenogener** [comment]
habanerolord

**Comment by Zenogener** [comment]
I don't know the extra numbers at the end

**Comment by Zenogener** [comment]
By the way I'm not able to access discord rn because I am on my chromebook driving home from somewhere

**Comment by jman1593** [comment]
thasts cool

**Comment by Zenogener** [comment]
Il be home hoe in 10 mins

**Comment by jman1593** [comment]
ok great

**Comment by Zenogener** [comment]
He gave up with making astro XP

**Comment by Zenogener** [comment]
He just wants to get good grades apparently.

**Comment by Zenogener** [comment]
Kinda  funny

**Comment by Zenogener** [comment]
He is very calm right now but I can tell he is raging inside.

**Comment by jman1593** [comment]
yeah. I bet he still working on it he just wants no one to know about it.

**Comment by Zenogener** [comment]
Probably

**Comment by Zenogener** [comment]
I know that max does not give up that type of stuff.

**Comment by Zenogener** [comment]
Also I wasn't able to get the recording on Friday because he was absent.

**Comment by Zenogener** [comment]
My proxy was blocked so I can't get to discord on my Chromebook.

**Comment by Zenogener** [comment]
I also realized you added and changed some stuff during lunch.

**Comment by Zenogener** [comment]
Shoot did he actually report it?

**Comment by Zenogener** [comment]
Yeah tomorrow I'ma be very mad at him during class, plus how do you know he reported it?

**Comment by jman1593** [comment]
yes, he did really report it. also, i have a friend who overheard him talking to the I.T. guy.

**Comment by jman1593** [comment]
also, i think he was bragging about it

**Comment by Zenogener** [comment]
lol

**Comment by Zenogener** [comment]
I saw him out on the field during lunch, and he seemed to be in a REALLY GOOD mood.

**Comment by jman1593** [comment]
yeah, I don't think he was expecting me to figure out. everyone is going to be VERY mad at him tomorrow

**Comment by Zenogener** [comment]
yeah, he must be sad that he has no friends, and today I actually saw him with people, and now, all over again he will have no friends, and I hope he understands that this is all because of what he is doing. 1. he CLAIMS he made strongdog so he does not have much friends because everyone knows that is not true 2. he is kinda weird and stupid 3. he finally decided to report strongdog and now everyone knows, so all over again he'll have no friens.

**Comment by jman1593** [comment]
i feel bad for him too, but for what he does, ngl he kind of deserves it. he has an illegal site with tons of pirated games and movies, and he is going to illegally (without permission) mine bitcoin on peoples computers while they are on his site.

**Comment by Zenogener** [comment]
...

**Comment by Zenogener** [comment]
🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦

**Comment by Zenogener** [comment]
Maybe we should just report HIS SITE

**Comment by Zenogener** [comment]
Frick that kid

**Comment by Zenogener** [comment]
I'm literally in the same class as him rn

**Comment by Zenogener** [comment]
His excuse  for reporting strongdog was "GITHUB.IO will be blocked eventually either way" But what he does not know is that there are so many different ways to bypass the blocking thing. also yeah I asked him if he actually reported it and he said yeah, so that info is not false.

**Comment by Zenogener** [comment]
You can just buy an actual domain and do the coding on GitHub. Which I think he knows

**Comment by Zenogener** [comment]
tbh I saw him literally playing on strongdog just barely lol

**Comment by Zenogener** [comment]
.............

**Comment by jman1593** [comment]
yeah. i was going to report his site anyways, if i buy a new domain for it to be unblocked at the school it has to be there for a few years so i can't do that, and, funny enough, he threatened to sue me if i didn't take his name down. I just made it simpler so it could be anyone (maximus weichers to max w)
